name: Amazon EPG Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "* */4 * * *"   # every 4 hrs

jobs:
  run-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Decode script from secret
        run: |
          echo "${{ secrets.AMAZON_SCRIPT_B64 }}" | base64 -d > amzn_epg.py

      - name: Run script
        run: |
          python amzn_epg.py

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: amazon-epg-files
          path: |
            amazon_epg.xml
            amazon_urls.txt
            amazon_id.json
